ALTER TABLE audit_entry DROP CONSTRAINT ck_audit_entry_action;
ALTER TABLE audit_entry ADD CONSTRAINT ck_audit_entry_action CHECK (action IN (
    'CASE_CREATED', 'DRAFT_LINES_REPLACED', 'CASE_SUBMITTED', 'SUPPLEMENT_REVISION_OPENED',
    'MATCH_RUN', 'REVIEW_SNAPSHOT_FROZEN', 'ITEM_MAPPED', 'SUPPLEMENT_REQUESTED',
    'CASE_REJECTED', 'APPROVE', 'DOCUMENT_UPLOAD_RESERVED', 'DOCUMENT_REGISTERED', 'ANALYSIS_RETRY_RESERVED'));
